<Button>:
    font_size: 24

<MyCalculator>:

    calc_field: calc_field

    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        TextInput:
            
            id: calc_field
            multiline: False
            readonly: True
            background_color: 255,255,255,1
            size_hint: (1, 0.3)
            padding_y:
            font_size: 56
            halign: "right"

        GridLayout:
            cols: 4
            Button:
                text:"("
                on_press: root.calc_symbol('(')
                background_color: 187/255, 183/255, 255/255, 0.8
            Button:
                text:")"
                on_press: root.calc_symbol(')')
                background_color: 187/255, 183/255, 255/255, 0.8
            Button:
                text:"+/-"
                on_press: root.turn_negative()
                background_color: 187/255, 183/255, 255/255, 0.8
            Button:
                text:"÷"
                on_press: root.calc_symbol('÷')
                background_color: 76/255, 71/255, 166/255, 1
            Button:
                text:"7"
                on_press: root.calc_symbol('7')
            Button:
                text:"8"
                on_press: root.calc_symbol('8')
            Button:
                text:"9"
                on_press: root.calc_symbol('9')
            Button:
                text:"x"
                on_press: root.calc_symbol('x')
                background_color: 76/255, 71/255, 166/255, 1
            Button:
                text:"4"
                on_press: root.calc_symbol('4')
            Button:
                text:"5"
                on_press: root.calc_symbol('5')
            Button:
                text:"6"
                on_press: root.calc_symbol('6')
            Button:
                text:"-"
                on_press: root.calc_symbol('-')
                background_color: 76/255, 71/255, 166/255, 1
            Button:
                text:"1"
                on_press: root.calc_symbol('1')
            Button:
                text:"2"
                on_press: root.calc_symbol('2')
            Button:
                text:"3"
                on_press: root.calc_symbol('3')
            Button:
                text:"+"
                on_press: root.calc_symbol('+')
                background_color: 76/255, 71/255, 166/255, 1
            Button:
                text: "."
                on_press: root.calc_symbol('.')
            Button:
                text: "0"
                on_press: root.calc_symbol('0')
            Button:
                text:"C"
                on_press: root.clear()
                background_color: 255/173, 52/173, 52/173, 1
            Button:
                text:"="
                on_press: root.calculate()
                background_color: 76/255, 71/255, 166/255, 1
                